/control/verbose 1
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/random/setSeeds 12345 67890
/gagg/geometry/mode bare
/gagg/source/particle optical
/gagg/source/mode fixed
/gagg/source/photonsPerEvent 1
/gagg/source/position 0 0 0 mm
/gagg/output/eventPrintModulo 1
/run/initialize

/vis/open OGL 1000x800-0+0
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 70 25 deg
/vis/viewer/set/style surface
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/zoom 1.5
/vis/scene/add/axes 0 0 0 2 cm
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton green
/vis/scene/endOfEventAction accumulate 10
/tracking/storeTrajectory 1
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

/run/beamOn 1
/vis/viewer/refresh
