/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/gagg/geometry/mode paper
/gagg/optics/gaggBulkAbsorption true
/gagg/source/mode isotropic
/gagg/source/photonsPerEvent 200
/gagg/source/position 0 0 0 mm
/gagg/output/eventPrintModulo 0
/run/initialize
/gagg/geometry/validate

/random/setSeeds 314159 271828
/gagg/output/csv results/a3/center_a.csv
/run/beamOn 100

/random/setSeeds 314159 271828
/gagg/output/csv results/a3/center_b.csv
/run/beamOn 100

/gagg/source/position 0 0 -10 mm
/random/setSeeds 314159 271828
/gagg/output/csv results/a3/z_m10.csv
/run/beamOn 100

/gagg/source/position 0 0 -5 mm
/random/setSeeds 314159 271828
/gagg/output/csv results/a3/z_m5.csv
/run/beamOn 100

/gagg/source/position 0 0 5 mm
/random/setSeeds 314159 271828
/gagg/output/csv results/a3/z_p5.csv
/run/beamOn 100

/gagg/source/position 0 0 10 mm
/random/setSeeds 314159 271828
/gagg/output/csv results/a3/z_p10.csv
/run/beamOn 100
