/control/verbose 1
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/random/setSeeds 271828 314159
/gagg/geometry/mode paper
/gagg/scoring/outputMode firstArrival
/gagg/optics/gaggBulkAbsorption true
/gagg/stageA/usePaperReflectivity true
/gagg/optics/scintillationTimeConstant 62.53 ns
/gagg/stageA/surface polishedvm2000air
/gagg/source/particle gamma
/gagg/source/mode fixed
/gagg/source/position 0 0 14.7 mm
/gagg/source/kineticEnergy 662 keV
/gagg/source/beamRadius 0 mm
/gagg/source/eventSeedBase 0
/gagg/optics/deferScintillationPhotons false
/gagg/output/eventPrintModulo 1
/run/initialize
/gagg/geometry/validate
/gagg/stageA/validate
/gagg/optics/validateScintillation

/vis/open OGL 1000x800-0+0
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 70 30 deg
/vis/viewer/set/style surface
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/zoom 2.0
/vis/scene/add/axes 0 0 0 2 cm
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma magenta
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/scene/endOfEventAction accumulate 1
/tracking/storeTrajectory 1
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

/run/beamOn 1
/vis/viewer/refresh
