/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/gagg/geometry/mode experiment
/gagg/stageA/surface none
/gagg/stageB/sideAirGap 0.1 mm
/gagg/stageB/blackHousingThickness 1.0 mm
/gagg/stageB/esrThickness 0.1 mm
/gagg/stageB/pmtWindowThickness 0.5 mm
/gagg/stageB/surfaceState all_polished
/gagg/stageB/sigmaAlpha 0.20 rad
/gagg/scoring/outputMode transmitted
/run/initialize
/gagg/geometry/validate
/gagg/stageB/validate
